export interface Product {
  id: number
  product_code: string // 型番（エンドユーザーには非表示）
  name: string
  category: string
  subtitle: string
  description: string
  images: string[]
  mainImage: string
  is_active: boolean
}

export const allProducts: Product[] = [
  // 掲載⚪︎の商品のみ（is_active: true）
  {
    id: 1,
    product_code: "KSSTB",
    name: "ヒンジ・スタンド付き缶バッジ",
    category: "多機能缶バッジ",
    subtitle: "ピン・ストラップ・スタンド付きで、使い方自在の多機能缶バッジ。",
    description: "バッグや洋服につけて日常的に楽しむのはもちろん、ストラップとしてスマホや小物に取り付けたり、スタンドで立てかけてインテリアとして飾ったりと幅広く活躍します。ヒンジやスタンドは使わない時には折りたためて使用できます。特許出願済み",
    images: ["/goods/goods_1_1.jpg", "/goods/goods_1_2.jpg", "/goods/goods_1_3.jpg"],
    mainImage: "/goods/goods_1_1.jpg",
    is_active: true,
  },
  {
    id: 2,
    product_code: "KSSTM",
    name: "マグネット付き缶バッジ",
    category: "多機能缶バッジ",
    subtitle: "つけるもはがすも自由自在、両面仕様の多機能缶バッジ。",
    description: "缶バッジを2つ組み合わせると、両面仕様になり、表裏で異なるデザインを楽しめるのも魅力。マグネット付きなので、冷蔵庫などに貼り付けても使用できます。特許出願済み",
    images: ["/goods/goods_2_1.jpg", "/goods/goods_2_2.jpg", "/goods/goods_2_3.jpg"],
    mainImage: "/goods/goods_2_1.jpg",
    is_active: true,
  },
  {
    id: 3,
    product_code: "KSWB",
    name: "連結缶バッジ",
    category: "多機能缶バッジ",
    subtitle: "つなげて楽しめる、ストラップ＆カニカン付き多機能缶バッジ。",
    description: "単体でバッグや服に付けて楽しむことはもちろん、複数の缶バッジを連結させて自分だけのオリジナルアクセサリーとしても活用でき、アクリルチャームをつけることも可能です。つなげて使わない時にはヒンジを折りたたんで使えます。特許出願済み",
    images: ["/goods/goods_3_1.jpg", "/goods/goods_3_2.jpg", "/goods/goods_3_3.jpg"],
    mainImage: "/goods/goods_3_1.jpg",
    is_active: true,
  },
  {
    id: 5,
    product_code: "KBST",
    name: "スタンド付き缶バッジ",
    category: "多機能缶バッジ",
    subtitle: "安全ピン＆スタンド付きで、身につけるも飾るも自由な缶バッジ。",
    description: "ピンで洋服やバッグに取り付ければ、手軽にお気に入りのデザインを身につけることができます。また、スタンドを使えば、デスクや棚に立てかけて飾ることも可能。スタンドは使わない時には折りたためて使用できます。特許出願済み",
    images: ["/goods/goods_5_1.jpg", "/goods/goods_5_2.jpg", "/goods/goods_5_3.jpg"],
    mainImage: "/goods/goods_5_1.jpg",
    is_active: true,
  },
  {
    id: 6,
    product_code: "KSST",
    name: "スタンド付き缶ストラップ",
    category: "多機能缶バッジ",
    subtitle: "ストラップにもディスプレイにも、スタンド付き缶ストラップ。",
    description: "ストラップとして日常的に持ち歩けるだけでなく、スタンドを利用することでディスプレイとしても活用できる2WAY仕様です。ヒンジやスタンドは使わない時には折りたためて使用できます。特許出願済み",
    images: ["/goods/goods_6_1.jpg", "/goods/goods_6_2.jpg", "/goods/goods_6_3.jpg"],
    mainImage: "/goods/goods_6_1.jpg",
    is_active: true,
  },
  {
    id: 9,
    product_code: "AST",
    name: "アクリルスタンド",
    category: "アクリル",
    subtitle: "安定感と透明感が特徴のディスプレイ向けアイテム。",
    description: "透明感と強度を兼ね備えたアクリル製のスタンド型アイテム。ディスプレイ性に優れ、飾って楽しむ商品として人気です",
    images: ["/goods/goods_9_1.jpg", "/goods/goods_9_2.jpg", "/goods/goods_9_3.jpg"],
    mainImage: "/goods/goods_9_1.jpg",
    is_active: true,
  },
  {
    id: 11,
    product_code: "AP-S",
    name: "動くアクリルスタンド",
    category: "アクリル",
    subtitle: "動くギミックで楽しめる、アクリル製の遊園地オブジェ。",
    description: "簡単に組み立てられ、ゆらゆらと揺れる様子は見ているだけでもワクワク感を味わえます",
    images: ["/goods/goods_11_1.jpg", "/goods/goods_11_2.jpg", "/goods/goods_11_3.jpg"],
    mainImage: "/goods/goods_11_1.jpg",
    is_active: true,
  },
  {
    id: 14,
    product_code: "ST-1",
    name: "缶バッジスタンド",
    category: "その他",
    subtitle: "丸型とハート型の缶バッジの展示に最適な専用台座。",
    description: "安全ピン付きの缶バッジを飾れる缶バッジスタンド。様々な大きさの缶バッジを飾れます。特許出願済み",
    images: ["/goods/goods_14_1.jpg", "/goods/goods_14_2.jpg", "/goods/goods_14_3.jpg"],
    mainImage: "/goods/goods_14_1.jpg",
    is_active: true,
  },
  {
    id: 15,
    product_code: "ST-2",
    name: "取り外し缶バッジスタンド",
    category: "その他",
    subtitle: "コンパクトタイプの専用台座",
    description: "缶バッジと一緒に小分け袋へ収まるほどのコンパクトサイズが魅力です。イベントやショップでの販売時にもセットしやすく、購入者がそのまま持ち帰ってすぐに飾れる便利さがあります。",
    images: ["/goods/goods_15_1.jpg", "/goods/goods_15_2.jpg", "/goods/goods_15_3.jpg"],
    mainImage: "/goods/goods_15_1.jpg",
    is_active: false,
  },
  // 掲載なし（is_active: false）の商品
  {
    id: 4,
    product_code: "KSWB-A",
    name: "チャーム付き缶ストラップ",
    category: "多機能缶バッジ",
    subtitle: "揺れるチャームがアクセント。",
    description: "缶バッジにチャームを組み合わせることで、動きと立体感をプラスした高付加価値アイテムです。",
    images: ["/goods/goods_4_1.jpg", "/goods/goods_4_2.jpg", "/goods/goods_4_3.jpg"],
    mainImage: "/goods/goods_4_1.jpg",
    is_active: false,
  },
  {
    id: 7,
    product_code: "KS",
    name: "缶ストラップ",
    category: "多機能缶バッジ",
    subtitle: "持ち歩きに適したコンパクトなデザイン。",
    description: "缶バッジのデザイン性を活かしたストラップ仕様。推しキャラクターやオリジナルイラストを持ち歩く楽しさを広げます。",
    images: ["/goods/goods_7_1.jpg", "/goods/goods_7_2.jpg", "/goods/goods_7_3.jpg"],
    mainImage: "/goods/goods_7_1.jpg",
    is_active: false,
  },
  {
    id: 8,
    product_code: "KT",
    name: "缶スタンド",
    category: "多機能缶バッジ",
    subtitle: "展示特化のデザインです。",
    description: "展示用に専用のスタンドを取り付けました。",
    images: ["/goods/goods_8_1.jpg", "/goods/goods_8_2.jpg", "/goods/goods_8_3.jpg"],
    mainImage: "/goods/goods_8_1.jpg",
    is_active: false,
  },
  {
    id: 10,
    product_code: "AS",
    name: "アクリルキーホルダー",
    category: "アクリル",
    subtitle: "実用性と視覚的訴求を両立したアクセサリー。",
    description: "厚みと高精細印刷による視覚的なインパクトが特徴。日常使いのアイテムとしても優れた訴求効果があります。",
    images: ["/goods/goods_10_1.jpg", "/goods/goods_10_2.jpg", "/goods/goods_10_3.jpg"],
    mainImage: "/goods/goods_10_1.jpg",
    is_active: false,
  },
  {
    id: 12,
    product_code: "AP-W",
    name: "アクリル観覧車",
    category: "アクリル",
    subtitle: "動くギミックで楽しめる、アクリル製の観覧車オブジェ。",
    description: "手で軽く回すと観覧車が回転し、ゆっくり動く様子は、見ているだけでワクワクする楽しさがあります。",
    images: ["/goods/goods_12_1.jpg", "/goods/goods_12_2.jpg", "/goods/goods_12_3.jpg"],
    mainImage: "/goods/goods_12_1.jpg",
    is_active: false,
  },
  {
    id: 13,
    product_code: "AP-B",
    name: "アクリルバイキング",
    category: "アクリル",
    subtitle: "ゆらゆら揺れて楽しめる、アクリル製バイキングオブジェ。",
    description: "バイキングの乗り物が揺れる様子は、まるで本物の遊園地のようで、見ているだけでもワクワク感を味わえます",
    images: ["/goods/goods_13_1.jpg", "/goods/goods_13_2.jpg", "/goods/goods_13_3.jpg"],
    mainImage: "/goods/goods_13_1.jpg",
    is_active: false,
  },
  // 説明文が未記入の商品たち（今後のために保持）
  {
    id: 18,
    product_code: "CS-d",
    name: "アンダーホログラム缶バッジ",
    category: "その他",
    subtitle: "キラキラ角度によって変わる色味を楽しめます。",
    description: "オーバーホログラムでも、アンダーホログラムにすることもどちらも可能です。ホログラムのパターンもいくつかありますのでお気軽にお問い合わせください。",
    images: ["/goods/goods_18_1.jpg", "/goods/goods_18_2.jpg", "/goods/goods_18_3.jpg"],
    mainImage: "/goods/goods_18_1.jpg",
    is_active: true,
  },
  {
    id: 19,
    product_code: "CS-c",
    name: "ラミネート缶バッジ",
    category: "多機能缶バッジ",
    subtitle: "",
    description: "",
    images: ["/goods/goods_19_1.jpg", "/goods/goods_19_2.jpg", "/goods/goods_19_3.jpg"],
    mainImage: "/goods/goods_19_1.jpg",
    is_active: false,
  },
  {
    id: 20,
    product_code: "CS-d",
    name: "キラキラ缶バッジ",
    category: "多機能缶バッジ",
    subtitle: "",
    description: "",
    images: ["/goods/goods_20_1.jpg", "/goods/goods_20_2.jpg", "/goods/goods_20_3.jpg"],
    mainImage: "/goods/goods_20_1.jpg",
    is_active: false,
  },
  {
    id: 21,
    product_code: "CS-e",
    name: "グリッター缶バッジ",
    category: "多機能缶バッジ",
    subtitle: "",
    description: "",
    images: ["/goods/goods_21_1.jpg", "/goods/goods_21_2.jpg", "/goods/goods_21_3.jpg"],
    mainImage: "/goods/goods_21_1.jpg",
    is_active: false,
  },
  {
    id: 22,
    product_code: "CS-f",
    name: "オーロラ缶バッジ",
    category: "多機能缶バッジ",
    subtitle: "",
    description: "",
    images: ["/goods/goods_22_1.jpg", "/goods/goods_22_2.jpg", "/goods/goods_22_3.jpg"],
    mainImage: "/goods/goods_22_1.jpg",
    is_active: false,
  },
  {
    id: 23,
    product_code: "CS-g",
    name: "カラー缶バッジ",
    category: "多機能缶バッジ",
    subtitle: "",
    description: "",
    images: ["/goods/goods_23_1.jpg", "/goods/goods_23_2.jpg", "/goods/goods_23_3.jpg"],
    mainImage: "/goods/goods_23_1.jpg",
    is_active: false,
  },
  {
    id: 24,
    product_code: "",
    name: "オーロラアクリル",
    category: "アクリル",
    subtitle: "",
    description: "",
    images: ["/goods/goods_24_1.jpg", "/goods/goods_24_2.jpg", "/goods/goods_24_3.jpg"],
    mainImage: "/goods/goods_24_1.jpg",
    is_active: false,
  },
  {
    id: 25,
    product_code: "",
    name: "缶付き髪ゴム",
    category: "多機能缶バッジ",
    subtitle: "",
    description: "",
    images: ["/goods/goods_25_1.jpg", "/goods/goods_25_2.jpg", "/goods/goods_25_3.jpg"],
    mainImage: "/goods/goods_25_1.jpg",
    is_active: false,
  },
  {
    id: 26,
    product_code: "",
    name: "両面チャーム付き缶ストラップ",
    category: "多機能缶バッジ",
    subtitle: "",
    description: "",
    images: ["/goods/goods_26_1.jpg", "/goods/goods_26_2.jpg", "/goods/goods_26_3.jpg"],
    mainImage: "/goods/goods_26_1.jpg",
    is_active: false,
  },
  {
    id: 27,
    product_code: "",
    name: "缶リース",
    category: "多機能缶バッジ",
    subtitle: "",
    description: "",
    images: ["/goods/goods_27_1.jpg", "/goods/goods_27_2.jpg", "/goods/goods_27_3.jpg"],
    mainImage: "/goods/goods_27_1.jpg",
    is_active: false,
  },
  {
    id: 28,
    product_code: "",
    name: "缶ネックレス",
    category: "多機能缶バッジ",
    subtitle: "",
    description: "",
    images: ["/goods/goods_28_1.jpg", "/goods/goods_28_2.jpg", "/goods/goods_28_3.jpg"],
    mainImage: "/goods/goods_28_1.jpg",
    is_active: false,
  },
]

// アクティブな商品のみを取得するヘルパー関数
export const getActiveProducts = (): Product[] => {
  return allProducts.filter(product => product.is_active)
}

export const categories = ["ALL", "多機能缶バッジ", "アクリル", "その他"]